name: expense_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  cloud_firestore:
  table_calendar:
  responsive_sizer: ^3.2.0
  gap:
  icons_launcher: ^2.1.7
  line_icons: ^2.0.3
  flutter_riverpod: ^2.3.6
  firebase_core:
  firebase_auth:
  firebase_remote_config:
  local_auth:
  url_launcher:
  flutter_easyloading:
  cached_network_image: ^3.3.1
  syncfusion_flutter_charts: ^22.2.5
  go_router: ^10.0.0
  google_sign_in:
  intl:
  freezed_annotation: ^2.1.0
  dartz: ^0.10.1
  injectable:
  timeago: ^3.5.0
  hooks_riverpod:
  shared_preferences:
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner:
  freezed: ^2.2.1
  injectable_generator:

flutter:
  uses-material-design: true

icons_launcher:
  image_path: "assets/images/app_icon.png"
  adaptive_background_color: '#000000'
  platforms:
    android:
      enable: true
    ios:
      enable: true

  assets:
    - assets/a.png
    - assets/
    - assets/gifs/  
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
